//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string visiting_hour { get; set; }
        public string academic { get; set; }
        public string expertice { get; set; }
        public string chamber_address { get; set; }
        public string chamber_contact { get; set; }
    
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
