//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int id { get; set; }
        public int patient_id { get; set; }
        public System.DateTime date_time { get; set; }
        public string note { get; set; }
        public string symptom1 { get; set; }
        public string symptom2 { get; set; }
        public string symptom3 { get; set; }
        public string symptom4 { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
