//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAide.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedaideEntities : DbContext
    {
        public MedaideEntities()
            : base("name=MedaideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DiagnosticCenter> DiagnosticCenters { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<DrugStore> DrugStores { get; set; }
        public DbSet<Journal> Journals { get; set; }
        public DbSet<MedList> MedLists { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<Prescription> Prescriptions { get; set; }
        public DbSet<Report> Reports { get; set; }
    }
}
