//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Journals = new HashSet<Journal>();
            this.MedLists = new HashSet<MedList>();
            this.Prescriptions = new HashSet<Prescription>();
            this.Reports = new HashSet<Report>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string contact { get; set; }
        public string emergency_contact { get; set; }
        public string gender { get; set; }
        public string blood_group { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
    
        public virtual ICollection<Journal> Journals { get; set; }
        public virtual ICollection<MedList> MedLists { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}
